apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-fastapi-postgresql-sa
  namespace: dev
  annotations:
    iam.gke.io/gcp-service-account: fastapi-db-iam-user@open-source-apps-001.iam.gserviceaccount.com
